/**
 * In-memory fakes of the three ports.
 *
 * The orchestrator is driven entirely through these in tests, so the whole
 * unattended flow is covered without spending subscription budget or touching
 * GitHub. Each fake records an ordered `calls` log; tests assert on that and on
 * the resulting state, never on internal helper calls.
 */

import { type Host, sameHost } from "../host.js";
import type {
  AgentPreflight,
  AgentRunner,
  StageName,
  StageRequest,
  StageResult,
} from "../ports/agent-runner.js";
import type {
  Candidate,
  CiOutcome,
  CreateIssue,
  CreatePullRequest,
  Issue,
  IssueComment,
  IssueRef,
  LabelSpec,
  PullRequestRef,
  SquashCommit,
  Tracker,
} from "../ports/tracker.js";
import type {
  CheckOutcome,
  HeldLock,
  KeptTranscripts,
  LockClaim,
  LockHolder,
  LockOutcome,
  LockTake,
  WorktreeRef,
  RebaseOutcome,
  RebaseState,
  StateFile,
  TicketState,
  Workspace,
  WorktreeFromRemote,
} from "../ports/workspace.js";
import { Hold } from "./hold.js";

export interface FakePullRequest extends CreatePullRequest {
  number: number;
  merged: boolean;
  /** What the merge composed, once it has happened. */
  squashCommit?: SquashCommit;
}

export class FakeTracker implements Tracker {
  user = "pipeline-user";
  /** Whether `gh` is logged in, as `init` reports it. */
  isAuthenticated = true;
  /** Whether squash merging is allowed, which `init` turns on. */
  squashMergeEnabled = false;
  /**
   * Whether a merged pull request's branch is deleted, which `init` turns on
   * and readiness asks for. Off, as on a repository GitHub has just made.
   */
  deleteBranchOnMergeEnabled = false;
  /** What GitHub calls this Target's default branch; the Run resolves from it. */
  defaultBranchName = "main";
  /**
   * The tag of the highest Version published on the pipeline's own repository,
   * as {@link latestVersionTag} answers. Nothing by default, which is the
   * answer a Target with no network gets and the one nothing is said over.
   */
  publishedVersionTag: string | undefined;
  /** When set, the lookup throws, as a `gh` that is not installed at all does. */
  versionTagFails = false;
  /** Every repository the Version lookup was asked about, in order. */
  versionTagLookups: string[] = [];
  labels = new Set<string>();
  /**
   * Labels GitHub adds after {@link listLabels} answers and before a create, as
   * it does while seeding a repository made seconds ago: not listed, but
   * there by the time one is created.
   */
  labelsArriving = new Set<string>();
  createdLabels: LabelSpec[] = [];
  issues = new Map<number, Issue>();
  comments: { issue: number; body: string }[] = [];
  /** Every issue the pipeline opened itself, in order, as it asked for it. */
  createdIssues: CreateIssue[] = [];
  /** Every in-place comment edit, in order, as {@link updateComment} took it. */
  updatedComments: { id: string; body: string }[] = [];
  /**
   * What the Host appends to every comment written, as a cloud Host appends
   * its "Generated by Claude Code" line. Nothing by default.
   */
  footer = "";
  pullRequests: FakePullRequest[] = [];
  ci: CiOutcome = { state: "passed" };
  /** Outcomes for the next CI waits, oldest first; `ci` answers once they run out. */
  ciQueue: CiOutcome[] = [];
  /** Open blockers per issue number; anything unlisted has none. */
  openBlockers = new Map<number, number>();
  /** Issue numbers closed by a merge, which drop out of the candidate list. */
  closed = new Set<number>();
  /** Fires after a squash merge, for tests where merging unblocks something. */
  onSquashMerge: ((pullRequest: number) => void) | undefined;
  ciWaits: { pullRequest: number; timeoutMs: number }[] = [];
  calls: string[] = [];
  private nextCommentId = 1;
  /** Where {@link waitForCi} parks, once a test has asked it to; see {@link holdsCi}. */
  private ciHold: Hold | undefined;

  addIssue(issue: Partial<Issue> & { number: number }): Issue {
    const full: Issue = {
      title: `Ticket ${issue.number}`,
      url: `https://github.com/acme/repo/issues/${issue.number}`,
      body: "- [ ] it works",
      closed: false,
      labels: ["ready-for-agent"],
      assignees: [],
      comments: [],
      subIssues: 0,
      blockedBy: [],
      ...issue,
    };
    // `closed` is the same fact the candidate list filters on, so a merge and a
    // seeded closed issue are read the same way.
    if (full.closed) this.closed.add(full.number);
    this.issues.set(full.number, full);
    return full;
  }

  issue(number: number): Issue {
    const issue = this.issues.get(number);
    if (!issue) throw new Error(`no such issue: #${number}`);
    return issue;
  }

  // Not in `calls`: a read, and one nothing about the Target changes over.
  async authenticated(): Promise<boolean> {
    return this.isAuthenticated;
  }

  async currentUser(): Promise<string> {
    return this.user;
  }

  // Not in `calls`: like the other reads, and a Run resolves the base branch
  // before it touches a Ticket, where the log is about what it wrote.
  async defaultBranch(): Promise<string> {
    return this.defaultBranchName;
  }

  // Not in `calls`: a read, and one about the pipeline's own repository rather
  // than about the Target this log is a record of.
  async latestVersionTag(repository: string): Promise<string | undefined> {
    this.versionTagLookups.push(repository);
    if (this.versionTagFails) throw new Error("gh: command not found");
    return this.publishedVersionTag;
  }

  async listLabels(): Promise<string[]> {
    return [...this.labels];
  }

  async createLabel(label: LabelSpec): Promise<boolean> {
    this.calls.push(`createLabel:${label.name}`);
    if (this.labelsArriving.delete(label.name)) this.labels.add(label.name);
    if (this.labels.has(label.name)) return false;
    this.createdLabels.push(label);
    this.labels.add(label.name);
    return true;
  }

  async enableSquashMerge(): Promise<void> {
    this.calls.push("enableSquashMerge");
    this.squashMergeEnabled = true;
  }

  // Not in `calls`: a read, which only decides whether a Target is ready.
  async deletesBranchOnMerge(): Promise<boolean> {
    return this.deleteBranchOnMergeEnabled;
  }

  async enableDeleteBranchOnMerge(): Promise<void> {
    this.calls.push("enableDeleteBranchOnMerge");
    this.deleteBranchOnMergeEnabled = true;
  }

  async getIssue(number: number): Promise<Issue> {
    return structuredClone({ ...this.issue(number), closed: this.closed.has(number) });
  }

  /** Numbered from 200 so a new issue is never mistaken for a seeded one. */
  async createIssue(issue: CreateIssue): Promise<IssueRef> {
    const number = 200 + this.createdIssues.length;
    this.calls.push(`createIssue:${number}`);
    this.createdIssues.push(issue);
    this.addIssue({
      number,
      title: issue.title,
      body: issue.body,
      labels: [...issue.labels],
    });
    return { number, url: `https://github.com/acme/repo/issues/${number}` };
  }

  /** Every open issue carrying `label`, deliberately in reverse number order. */
  async listCandidates(label: string): Promise<Candidate[]> {
    this.calls.push(`listCandidates:${label}`);
    return [...this.issues.values()]
      .filter((issue) => !this.closed.has(issue.number) && issue.labels.includes(label))
      .sort((a, b) => b.number - a.number)
      .map((issue) => ({
        number: issue.number,
        title: issue.title,
        assignees: [...issue.assignees],
        openBlockers: this.openBlockers.get(issue.number) ?? 0,
      }));
  }

  async assign(number: number, user: string): Promise<void> {
    this.calls.push(`assign:${number}:${user}`);
    this.issue(number).assignees.push(user);
  }

  async unassign(number: number, user: string): Promise<void> {
    this.calls.push(`unassign:${number}:${user}`);
    const issue = this.issue(number);
    issue.assignees = issue.assignees.filter((a) => a !== user);
  }

  async addLabel(number: number, label: string): Promise<void> {
    this.calls.push(`addLabel:${number}:${label}`);
    const issue = this.issue(number);
    if (!issue.labels.includes(label)) issue.labels.push(label);
  }

  async removeLabel(number: number, label: string): Promise<void> {
    this.calls.push(`removeLabel:${number}:${label}`);
    const issue = this.issue(number);
    issue.labels = issue.labels.filter((l) => l !== label);
  }

  async comment(number: number, body: string): Promise<IssueComment> {
    // A comment on an issue the fake never heard of is the tracker refusing a
    // write, which is what a Stage that invented a Ticket number would get.
    this.issue(number);
    this.calls.push(`comment:${number}`);
    body += this.footer;
    this.comments.push({ issue: number, body });
    // A comment is on the issue from now on, which is what the next getIssue
    // has to see: the pipeline finds its own comments again by marker.
    const posted: IssueComment = { id: `c${this.nextCommentId++}`, body };
    this.issues.get(number)?.comments.push(posted);
    return { ...posted };
  }

  async updateComment(id: string, body: string): Promise<void> {
    this.calls.push(`updateComment:${id}`);
    body += this.footer;
    this.updatedComments.push({ id, body });
    const comment = [...this.issues.values()]
      .flatMap((issue) => issue.comments)
      .find((candidate) => candidate.id === id);
    if (!comment) throw new Error(`no such comment: ${id}`);
    comment.body = body;
  }

  async updateIssueBody(number: number, body: string): Promise<void> {
    this.calls.push(`updateIssueBody:${number}`);
    this.issue(number).body = body;
  }

  async createPullRequest(pr: CreatePullRequest): Promise<PullRequestRef> {
    const number = 100 + this.pullRequests.length;
    this.calls.push(`createPullRequest:${number}:${pr.draft ? "draft" : "ready"}`);
    this.pullRequests.push({ ...pr, number, merged: false });
    return { number, url: `https://github.com/acme/repo/pull/${number}` };
  }

  async convertPullRequestToDraft(number: number): Promise<void> {
    this.calls.push(`convertPullRequestToDraft:${number}`);
    this.pullRequest(number).draft = true;
  }

  async markPullRequestReady(number: number): Promise<void> {
    this.calls.push(`markPullRequestReady:${number}`);
    this.pullRequest(number).draft = false;
  }

  async updatePullRequestBody(number: number, body: string): Promise<void> {
    this.calls.push(`updatePullRequestBody:${number}`);
    this.pullRequest(number).body = body;
  }

  /** Queue the outcome of the next CI wait, overriding {@link ci} once. */
  queueCi(outcome: CiOutcome): this {
    this.ciQueue.push(outcome);
    return this;
  }

  /**
   * Hold every CI wait open until the test releases it.
   *
   * A Ticket parked here is inside the Landing with its pull request open, which
   * is where a test puts one to watch what another Ticket does meanwhile.
   */
  holdsCi(): Hold {
    const hold = new Hold();
    this.ciHold = hold;
    return hold;
  }

  async waitForCi(number: number, timeoutMs: number): Promise<CiOutcome> {
    this.calls.push(`waitForCi:${number}`);
    this.ciWaits.push({ pullRequest: number, timeoutMs });
    await this.ciHold?.reached();
    return this.ciQueue.shift() ?? this.ci;
  }

  async squashMerge(number: number, commit: SquashCommit): Promise<void> {
    this.calls.push(`squashMerge:${number}`);
    const pr = this.pullRequest(number);
    pr.merged = true;
    pr.squashCommit = commit;
    // The PR body closes the Ticket, which is how a Run's Frontier shrinks.
    const closes = /Closes #(\d+)/.exec(pr.body);
    if (closes) this.closed.add(Number.parseInt(closes[1] as string, 10));
    this.onSquashMerge?.(number);
  }

  pullRequest(number: number): FakePullRequest {
    const pr = this.pullRequests.find((candidate) => candidate.number === number);
    if (!pr) throw new Error(`no such pull request: #${number}`);
    return pr;
  }
}

export class FakeAgentRunner implements AgentRunner {
  requests: StageRequest[] = [];
  /** What the preflight answers; a Target with everything installed by default. */
  preflightAnswer: AgentPreflight = { runs: true, plugin: true };
  /** How many times `init` asked, so a test can say it asked once. */
  preflights = 0;
  /** Queued results per Stage; the last one is reused once the queue drains. */
  private queued = new Map<StageName, StageResult[]>();
  /** What each Stage leaves behind besides its result; see {@link leaves}. */
  private effects = new Map<StageName, () => void>();
  /** Where a Stage parks before it comes back; see {@link holds}. */
  private held = new Map<StageName, Hold>();

  constructor(private readonly defaults: Partial<Record<StageName, StageResult>> = {}) {}

  /**
   * Say what a Stage does to the world every time it runs, on top of returning
   * a result — committing on the branch, above all, which the fake Workspace
   * holds. Registering no effect is how a test says the session changed
   * nothing, and registering a second one replaces the first.
   */
  leaves(stage: StageName, effect: () => void): this {
    this.effects.set(stage, effect);
    return this;
  }

  /**
   * Hold a Stage open: every run of it parks once it has started and stays
   * there until the test releases the hold.
   *
   * What a test uses to say where a Ticket is while it watches another one — a
   * Ticket inside a held conflict Stage is inside the Landing, and one inside a
   * held fix Stage has given the Landing up. Whatever the Stage
   * {@link leaves} behind it leaves on arrival, as a real session that committed
   * and then ran long does.
   */
  holds(stage: StageName): Hold {
    const hold = new Hold();
    this.held.set(stage, hold);
    return hold;
  }

  /** Queue the next result for a Stage, overriding the default. */
  queue(stage: StageName, result: Partial<StageResult>): this {
    const existing = this.queued.get(stage) ?? [];
    existing.push({ ...stageResult(), ...result });
    this.queued.set(stage, existing);
    return this;
  }

  prompts(stage: StageName): string[] {
    return this.requests.filter((r) => r.stage === stage).map((r) => r.prompt);
  }

  stages(): StageName[] {
    return this.requests.map((request) => request.stage);
  }

  async preflight(): Promise<AgentPreflight> {
    this.preflights += 1;
    return this.preflightAnswer;
  }

  async run(request: StageRequest): Promise<StageResult> {
    this.requests.push(request);
    // Before the result is read, and whatever it turns out to be: a session
    // that committed and then ran out of turns still committed.
    this.effects.get(request.stage)?.();
    await this.held.get(request.stage)?.reached();
    const queued = this.queued.get(request.stage);
    if (queued && queued.length > 0) return queued.shift() as StageResult;
    return this.defaults[request.stage] ?? stageResult();
  }
}

export function stageResult(overrides: Partial<StageResult> = {}): StageResult {
  return {
    ok: true,
    commandLine: "claude -p ...",
    transcriptPath: "/logs/transcript.jsonl",
    turns: 7,
    durationMs: 1_000,
    ...overrides,
  };
}

/** The Run lock a {@link FakeWorkspace} keeps, and whether the Run it names is running. */
export interface FakeLock {
  holder: LockHolder;
  running: boolean;
}

/** The Host a {@link FakeWorkspace} runs on, unless a test says otherwise. */
export const THIS_HOST: Host = { kind: "workstation", id: "desk-machine-id", name: "desk" };

/** Another Host of the same Target: a cloud session, as a Run from the app has. */
export const ANOTHER_HOST: Host = { kind: "cloud", id: "session_01other", name: "runsc" };

export class FakeWorkspace implements Workspace {
  /** worktree path → branch, for the worktrees that currently exist. */
  worktrees = new Map<string, string>();
  /**
   * The branches this repo has, which outlive their worktrees: a test seeds one
   * to stand for a branch a human left behind.
   */
  branches = new Set<string>();
  /**
   * The branches the remote has: a push puts its branch there, a test seeds one
   * to stand for work another Host pushed, and deleting one takes it away.
   */
  remoteBranches = new Set<string>();
  /**
   * Branches whose copy on this Host has parted from the one on the remote,
   * each carrying commits the other lacks: a test seeds one for another Host
   * that moved on while this one held work it never pushed.
   */
  partedBranches = new Set<string>();
  calls: string[] = [];
  /** The branch's commit subjects, oldest first, as an implement Stage leaves them. */
  commits = ["feat(cli): do the thing (#2)", "test(cli): cover the thing (#2)"];
  coAuthorList: string[] = [];
  /**
   * The paths no commit carries, as a Stage that stopped short of committing
   * leaves them. Empty is a worktree that is exactly its branch tip, and a
   * discard empties it, as `git reset --hard && git clean` does.
   */
  uncommitted: string[] = [];
  /** Check outcomes that stick, per command; a command with none always passes. */
  checkOutcomes = new Map<string, CheckOutcome>();
  /** Outcomes for the next runs of a command; `checkOutcomes` answers once they run out. */
  checkQueue = new Map<string, CheckOutcome[]>();
  ranChecks: { command: string; cwd: string; timeoutMs: number }[] = [];
  rebaseOutcome: RebaseOutcome = { ok: true };
  /** Outcomes for the next rebases, oldest first; `rebaseOutcome` answers once they run out. */
  rebaseQueue: RebaseOutcome[] = [];
  /** The branch each worktree was created from, in order. */
  branchedFrom: string[] = [];
  /** The branch each rebase replayed onto, in order. */
  rebasedOnto: string[] = [];
  /**
   * Every base branch the pipeline handed any operation, in order — the reads
   * that only compute a range included, so a test can say the whole Ticket was
   * worked against one branch and nothing quietly kept its own `main`.
   */
  basesGiven: string[] = [];
  /** What the worktree looks like once the conflict Stage has had its turn. */
  rebaseStateAfterStage: RebaseState = { resolved: true };
  aborts = 0;
  pushes: { cwd: string; branch: string }[] = [];
  /** The branch each post-merge pull brought the main checkout to, in order. */
  pulledBase: string[] = [];
  /**
   * Each Ticket's State on the remote's state branch, as a Run on any Host
   * would read it. A test seeds one to stand for what an earlier Run left,
   * readable or not. Reads and writes of it stay out of `calls`: a Ticket
   * touches its State at every step, and a test reading the order of its git
   * would otherwise have to step round them.
   */
  states = new Map<number, StateFile>();
  /**
   * The Runs whose transcripts each handed-off Ticket keeps beside its State,
   * in the order they were kept. They go when the State does.
   */
  transcripts = new Map<number, string[]>();
  /**
   * What every write of the State fails with, when set: storage that will not
   * take it, which takes transcripts no better.
   */
  stateWriteFailure: Error | undefined;
  /** What every pull of the base branch fails with, when set: a checkout git cannot fast-forward. */
  pullBaseFailure: Error | undefined;
  /**
   * The Run lock as it stands on the remote, and whether the Run it names is
   * still running. Undefined is a lock nobody holds.
   */
  get lock(): FakeLock | undefined {
    return this.remoteLock.current;
  }

  set lock(lock: FakeLock | undefined) {
    this.remoteLock.current = lock;
  }

  /** Where {@link lock} is kept, which {@link anotherHost} shares like the rest of the remote. */
  private remoteLock: { current?: FakeLock | undefined } = {};
  /** The Host this Workspace runs on, which a lock's holder is compared with. */
  host: Host = THIS_HOST;

  /**
   * The same Target seen from another Host: the remote — its branches, every
   * Ticket's State and the Run lock — shared with this one, and none of this
   * Host's worktrees or branches. What a Run on this Host pushes or records, a
   * Run on that one finds.
   */
  anotherHost(): FakeWorkspace {
    const other = new FakeWorkspace();
    other.host = ANOTHER_HOST;
    other.remoteBranches = this.remoteBranches;
    other.states = this.states;
    other.transcripts = this.transcripts;
    other.remoteLock = this.remoteLock;
    return other;
  }

  /** The State `ticket` keeps, when it is one a Run can resume from. */
  state(ticket: number): TicketState | undefined {
    const file = this.states.get(ticket);
    return file?.readable === true ? file.state : undefined;
  }

  /** Seed the State an earlier Run left for its Ticket. */
  recordState(state: TicketState): this {
    this.states.set(state.ticket, { readable: true, state: { ...state } });
    return this;
  }

  /** Fail `command` every time the pipeline runs it. */
  failCheck(command: string, output: string): this {
    this.checkOutcomes.set(command, { ok: false, output, timedOut: false });
    return this;
  }

  /** Conflict on the next rebase only: a conflict the conflict Stage then resolves. */
  conflictOnce(conflict: string): this {
    this.rebaseQueue.push({ ok: false, conflict });
    return this;
  }

  /** Fail `command` on its next run only: a Check a fix Stage then mends. */
  failCheckOnce(command: string, output: string): this {
    return this.queueCheck(command, { ok: false, output, timedOut: false });
  }

  /** Time `command` out every time the pipeline runs it. */
  timeOutCheck(command: string, output: string): this {
    this.checkOutcomes.set(command, { ok: false, output, timedOut: true });
    return this;
  }

  /** Time `command` out on its next run only. */
  timeOutCheckOnce(command: string, output: string): this {
    return this.queueCheck(command, { ok: false, output, timedOut: true });
  }

  private queueCheck(command: string, outcome: CheckOutcome): this {
    const queued = this.checkQueue.get(command) ?? [];
    queued.push(outcome);
    this.checkQueue.set(command, queued);
    return this;
  }

  async createWorktree({ path, branch }: WorktreeRef, base: string): Promise<void> {
    this.calls.push(`createWorktree:${branch}`);
    this.branchedFrom.push(base);
    this.basesGiven.push(base);
    this.worktrees.set(path, branch);
    this.branches.add(branch);
  }

  async hasWorktree({ path, branch }: WorktreeRef): Promise<boolean> {
    this.calls.push(`hasWorktree:${branch}`);
    return this.worktrees.get(path) === branch;
  }

  async hasBranch(branch: string): Promise<boolean> {
    this.calls.push(`hasBranch:${branch}`);
    return this.branches.has(branch);
  }

  async worktreeFromRemote({ path, branch }: WorktreeRef): Promise<WorktreeFromRemote> {
    this.calls.push(`worktreeFromRemote:${branch}`);
    const here = this.worktrees.get(path) === branch;
    if (!this.remoteBranches.has(branch)) return here ? "kept" : "gone";
    if (this.partedBranches.has(branch) && (here || this.branches.has(branch))) {
      return "parted";
    }
    if (here) return "kept";
    this.worktrees.set(path, branch);
    this.branches.add(branch);
    return "made";
  }

  async removeWorktree({ path, branch }: WorktreeRef): Promise<void> {
    this.calls.push(`removeWorktree:${branch}`);
    this.worktrees.delete(path);
    this.branches.delete(branch);
  }

  async commitSubjects(branch: string, base: string): Promise<string[]> {
    this.calls.push(`commitSubjects:${branch}`);
    this.basesGiven.push(base);
    return [...this.commits];
  }

  async coAuthors(branch: string, base: string): Promise<string[]> {
    this.calls.push(`coAuthors:${branch}`);
    this.basesGiven.push(base);
    return [...this.coAuthorList];
  }

  async runCheck(command: string, cwd: string, timeoutMs: number): Promise<CheckOutcome> {
    this.calls.push(`runCheck:${command}`);
    this.ranChecks.push({ command, cwd, timeoutMs });
    return (
      this.checkQueue.get(command)?.shift() ??
      this.checkOutcomes.get(command) ?? { ok: true, output: "" }
    );
  }

  async uncommittedPaths(cwd: string): Promise<string[]> {
    this.calls.push(`uncommittedPaths:${cwd}`);
    return [...this.uncommitted];
  }

  async discardChanges(cwd: string): Promise<void> {
    this.calls.push(`discardChanges:${cwd}`);
    this.uncommitted = [];
  }

  async rebase(_cwd: string, base: string): Promise<RebaseOutcome> {
    this.calls.push("rebase");
    this.rebasedOnto.push(base);
    this.basesGiven.push(base);
    return this.rebaseQueue.shift() ?? this.rebaseOutcome;
  }

  async rebaseState(_cwd: string, base: string): Promise<RebaseState> {
    this.calls.push("rebaseState");
    this.basesGiven.push(base);
    return this.rebaseStateAfterStage;
  }

  async abortRebase(): Promise<void> {
    this.calls.push("abortRebase");
    this.aborts += 1;
  }

  async push(cwd: string, branch: string): Promise<void> {
    this.calls.push(`push:${branch}`);
    // git runs in a directory or it does not run at all: a push out of a
    // worktree that was never created fails with ENOENT, and a fake that
    // shrugged it off would let the pipeline go on asking for one.
    if (!this.worktrees.has(cwd)) {
      throw new Error(`ENOENT: no such file or directory, chdir '${cwd}'`);
    }
    this.pushes.push({ cwd, branch });
    this.remoteBranches.add(branch);
  }

  // Not in `calls`: a read, which only decides what a hand-off comment says.
  async hasRemoteBranch(branch: string): Promise<boolean> {
    return this.remoteBranches.has(branch);
  }

  async deleteRemoteBranch(branch: string): Promise<void> {
    this.calls.push(`deleteRemoteBranch:${branch}`);
    this.remoteBranches.delete(branch);
  }

  async pullBase(base: string): Promise<void> {
    this.calls.push("pullBase");
    if (this.pullBaseFailure !== undefined) throw this.pullBaseFailure;
    this.pulledBase.push(base);
    this.basesGiven.push(base);
  }

  async readState(ticket: number): Promise<TicketState | undefined> {
    const state = this.state(ticket);
    return state === undefined ? undefined : { ...state };
  }

  async readAllStates(): Promise<StateFile[]> {
    return [...this.states.entries()]
      .sort(([first], [second]) => first - second)
      .map(([, file]) => file);
  }

  async writeState(state: TicketState): Promise<void> {
    if (this.stateWriteFailure !== undefined) throw this.stateWriteFailure;
    this.recordState(state);
  }

  async removeState(ticket: number): Promise<void> {
    this.states.delete(ticket);
    this.transcripts.delete(ticket);
  }

  /**
   * Kept whatever the Run ran: the fake has no transcripts on disk to count,
   * so it keeps the Run's name, which is what a test asks after.
   */
  async keepTranscripts(ticket: number, runId: string): Promise<KeptTranscripts | undefined> {
    if (this.stateWriteFailure !== undefined) throw this.stateWriteFailure;
    this.transcripts.set(ticket, [...(this.transcripts.get(ticket) ?? []), runId]);
    return { branch: "agent-pipeline/state", path: `ticket-${ticket}/${runId}/` };
  }

  async takeRunLock(claim: LockClaim): Promise<LockTake> {
    this.calls.push("takeRunLock");
    const held = this.heldLock();
    if (held !== undefined) return { outcome: "held", ...held };
    if (this.lock !== undefined) return { outcome: "abandoned" };
    this.lock = { holder: { host: this.host, ...claim }, running: true };
    return { outcome: "taken" };
  }

  async takeOverRunLock(claim: LockClaim): Promise<LockOutcome> {
    this.calls.push("takeOverRunLock");
    const held = this.heldLock();
    if (held !== undefined) return { outcome: "held", ...held };
    this.lock = { holder: { host: this.host, ...claim }, running: true };
    return { outcome: "taken" };
  }

  async runLockHolder(): Promise<HeldLock | undefined> {
    this.calls.push("runLockHolder");
    return this.heldLock();
  }

  /**
   * The lock as a Run on this Host sees it: held when its Run is running, and
   * always when it is held from another Host, whose process nothing here sees.
   */
  private heldLock(): HeldLock | undefined {
    if (this.lock === undefined) return undefined;
    const { holder, running } = this.lock;
    const onAnotherHost = !sameHost(holder.host, this.host);
    return onAnotherHost || running ? { holder, onAnotherHost } : undefined;
  }

  async releaseRunLock(): Promise<void> {
    this.calls.push("releaseRunLock");
    this.lock = undefined;
  }
}
